config/routes.rb
Rails.application.routes.draw do
# Authentication
  devise_for :users, :skip => [:sessions, :registrations]
    as :user do
       # session handling
      get '/login' => 'devise/sessions#new', :as => :new_user_session
      post '/login' => 'devise/sessions#create', :as => :user_session
      delete '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
      # joining md5(wakeupilot)
       get   '/4c69aabcef98b458943de1bb0ac59469' => 'devise/registrations#new',    as: :new_user_registration
       post  '/4c69aabcef98b458943de1bb0ac59469' => 'devise/registrations#create', as: :user_registration

       # settings & cancellation
      get '/cancel'   => 'devise/registrations#cancel', as: :cancel_user_registration
      get '/settings' => 'devise/registrations#edit',   as: :edit_user_registration
      put '/settings' => 'devise/registrations#update'

      # account deletion
      delete '' => 'devise/registrations#destroy'


    end

#Restrict access to sign_up page only for signed in users
#devise_for :users, :controllers => { :registrations => 'registrations'}
##
  #authenticate :user do
    #resources :logs, only: [ :create,:destroy]
  #end
    #resources :logs, only: [:index, :show]
##
namespace :api, defaults: {formats: 'json'} do
  namespace :v1 do
    resources :logs
  end
end

resources :logs
resources :players do
  #match :create, via: [:post],  on: :collection
end
resources :games
root "logs#index"
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :player

  def self.to_csv

    CSV.generate do |csv|
      csv << ["Nom", "Age", "Genre", "Total", "Ball touche", "Reference", "Date "]
      all.each do |game|

          csv << [game.player_name, game.player_age, game.player_genre, game.total_touches, game.ball_touched, game.first_time, game.created_at]

      end
    end
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :games

  def self.to_csv

    CSV.generate do |csv|
      csv << [:username, :age, :genre]
      all.each do |player|
        if( !player.username.blank? || !player.age.blank? || !player.genre.blank?)
          csv << [player.username, player.age, player.genre]
        end
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable,
  #       :recoverable, :rememberable, :trackable, :validatable

  #removed registerable from devise
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  #no need for authentication
  #before_action :authenticate_user!

  def index
    @games = Game.all.order('created_at DESC').page(params[:page])
    @count = @games.count

    respond_to do |format|
        format.html
        format.json { @games = Game.all ; render json: @games }
        format.csv  { @games = Game.all ; send_data @games.to_csv }
        format.pdf  do
          @games = Game.all
          pdf = Prawn::Document.new

          pdf.text "Statistiques WakeUpPilot"
          pdf.move_down 10
          #pdf.table
          data = @games.map do |game|
            if game.first_time
              first = "OUI"
            else
              first = "NON"
            end
            [
                  game.player_name,
                  game.player_age,
                  game.player_genre,
                  game.total_touches,
                  game.ball_touched,
                  first,
                  game.created_at.strftime("%d/%m/%Y  %H:%M")
            ]
          end
          pdf.table [["Nom", "Age", "Genre", "Total", "Ball touche", "Reference", "Crée le"]] + data
          send_data pdf.render, filename: "wakeuppilot.pdf", type: "application/pdf", disposition: ""
        end
    end
  end

  def create
    @game = Game.new(game_params)
    @game.save
    redirect_to root_url
  end

  def show
    @game = Game.find(params[:id])

    respond_to do |format|
        format.html { @game.destroy ; redirect_to root_url and return}
        format.json { render json: @game }
    end
    #Log.find(params[:id]).destroy
  end

  def destroy
    Game.find(params[:id]).destroy
    redirect_to root_url
  end

  private
	# Use callbacks to share common setup or constraints between actions.
	    def set_game
	      @game = Game.find(params[:id])
	    end

		def game_params
			params.require(:game).permit(:ball_touched, :total_touches, :first_time, :player_id, :player_name, :player_age, :player_genre )
		end

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]

	def index
		@logs = Log.paginate(:page => params[:page],:per_page => 10).order('created_at DESC')
		#expires_in 5.minutes, public: true
		@count = Log.count

		#fresh_when @logs
		#fresh_when @count

		respond_to do |format|
			  format.html
			  format.json { @all_logs = Log.all ; render json: @all_logs }
		end

	end

	def create

		@log = Log.new(log_params)
		@log.save
		redirect_to root_url
	end

	def show
		@log = Log.find(params[:id])

		respond_to do |format|
			  format.html { @log.destroy ; redirect_to root_url and return}
			  format.json { render json: @log }
		end
		#Log.find(params[:id]).destroy
	end

	def destroy
		Log.find(params[:id]).destroy
		redirect_to root_url
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	    def set_log
	      @log = Log.find(params[:id])
	    end

		def log_params
			params.require(:log).permit(:title, :body)
		end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  #no need for authentication
  #before_action :authenticate_user!

  def index
    @players = Player.all.order('created_at DESC').page(params[:page])
    @count = @players.count
    respond_to do |format|
        format.html
        format.json { @players = Player.all ; render json: @players }
        format.csv  { @players = Player.all ; send_data @players.to_csv }
        format.pdf  do
          @players = Player.all
          pdf = Prawn::Document.new

          pdf.text "Statistiques WakeUpPilot"
          pdf.move_down 10
          #pdf.table
          data = @players.map do |player|
            [
                  player.username,
                  player.age,
                  player.genre
            ]
          end
          pdf.table [["Username", "Age", "Genre"]] + data
          send_data pdf.render, filename: "wakeuppilot.pdf", type: "application/pdf", disposition: ""
        end
    end
  end

  def create
    #don't record array if empty
    #bad dirty code!! :( 
    if !player_params[:player].empty?
      Player.create(player_params[:player])
    end

    respond_to do |format|
       format.html {redirect_to players.json_url }
       format.json {  @players = Player.all ; render json: @players }
    end
  end

  def show
    @player = Player.find(params[:id])

    respond_to do |format|
        format.html { @player.destroy ; redirect_to root_url and return}
        format.json { render json: @player }
    end
    #Log.find(params[:id]).destroy
  end

  def destroy
    Player.find(params[:id]).destroy
    redirect_to root_url
  end

  private
	# Use callbacks to share common setup or constraints between actions.
	    def set_player
	      @player = Player.find(params[:id])
	    end

		def player_params
			params.permit(player: [:username, :age, :genre])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/games/index.html.erb
<h1>Statistiques<small> (<%= @count %>)</small></h1>

<div class="table-responsive">
  <div class="text-center">
      <%= paginate @games%><h3><small class="pull-right">Télécharger en <%= link_to 'format csv', games_path(format: :csv) %> | <%= link_to 'format pdf', games_path(format: :pdf) %></small><h3>
  </div>
  <table class="table table-condensed table-hover table-bordered">
    <thead>
        <tr>
            <th>#ID</th>
            <th>Nom</th>
            <th>Age</th>
            <th>Genre</th>
            <th>Total</th>
            <th>Ball touché</th>
            <th>Reference</th>
            <th>Date</th>

        </tr>
    </thead>
    <tbody>
      <% @games.each do |game|%>
        <tr>
          <td><%= game.id%></td>
          <td><%= game.player_name%></td>
          <td><%= game.player_age%></td>
          <td><%= game.player_genre%></td>
          <td><%= game.total_touches%></td>
          <td><%= game.ball_touched%></td>
          <td>
              <%if(game.first_time)%>
                  OUI
              <%else%>
                  NON
              <%end%>
          </td>
          <td><%= game.created_at.strftime("%d/%m/%Y  %H:%M")%></td>

        </tr>
      <%end%>
    </tbody>

  </table>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse " role="navigation">

			<div class="container">
			 	<!-- Brand and toggle get grouped for better mobile display -->
				    <div class="navbar-header">
				      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse">
				        <span class="sr-only">Toggle navigation</span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				      </button>
				    <div><%= link_to "WakeUpPilot", root_path, id: "logo" %></div>
				 </div>

				<div class="collapse navbar-collapse navbar-ex1-collapse" id="bs-navbar-collapse">

					<ul class="nav navbar-nav navbar-right">

            <% if user_signed_in? %>
						<li>  <%= link_to  current_user.email, edit_user_registration_path %> </li>
						<li>  <%= link_to  "Statistiques", games_path %> </li>
            <li>  <%= link_to "Se déconnecter", '/logout', method: :delete %>  </li>
						<% else %>
            <li>
              <%= link_to "Login", new_user_session_path %>
            </li>
						<%end%>
					</ul>

				</div>
			</div>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Wakeuppilot</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
</head>
<body>
  	<%=render 'layouts/header'%>
    <div class = "container">
      <div class="col-md-10 col-md-offset-1 content">
        <%= yield %>
      </div>
    </div>
</body>
</html>

app/views/logs/index.html.erb
<!-- Page header -->
<div class="page-header">
    <h1>Fiches Conseil <small class="small-header">(<%=@count %> conseils)</small></h1>
</div>

<!-- /Page header -->
<div class="login-link">
  <% if user_signed_in? %>
   <%= link_to "Se déconnecter", '/logout', method: :delete %>
  <% else %>
    <%= link_to "Login", new_user_session_path %>
  <%end%>
</div>

<!-- The form-->
<%=form_for :log, url: logs_path do |f| %>


	<div class="form-group">
		<%=f.text_field :title, class: "form-control",  placeholder: "Entrer le titre de la fiche conseil ici ..."%>
	</div>
	<div class="input-body">
	<div class="form-group input-body">
		<%=f.text_area :body, class: "form-control", placeholder: "Entrer la description de la fiche conseil ici..."%>
	</div>

	<%= f.submit "Enregistrer",  class: "btn btn-lg btn-primary pull-right", style: "margin-bottom:10px" %>
	</div>
<%end%>
<!-- /The form-->

<!-- Timeline -->
<div class="timeline">


    <div class="line text-muted"></div>

    <%@size = @logs.size %>
	<% @logs.each do |log|%>
		<!-- Separator -->
	        <div class="separator"></div>
        <!-- /Separator -->
	 <!-- Panel -->
        <article class="panel panel-primary panel-outline">
            <!-- Icon -->
            <div class="panel-heading icon">
                <i class="glyphicon glyphicon-thumbs-up"></i>
            </div>

                <h2 class="panel-title">#<%=@size%>: <%=log.title.split.map(&:capitalize).join(' ')%></h2>
            <!-- /Heading -->
              <%@size = @size - 1 %>
            <!-- Body -->
            <div class="panel-body">
               <%=log.body.capitalize%><br/>
               <small class="pull-right"><span class = "small-time">crée le <%=log.created_at.strftime("%d/%m/%Y")%> à <%=log.created_at.strftime("%H:%M")%> | </span><%= link_to 'Effacer la fiche', log, method: :delete, data: { confirm: 'Are you sure?' }%></small>
            </div>
            <!-- /Body -->

            <!-- Footer -->
            <div class="panel-footer">
              blablabla
				<small class="pull-right"><%= time_ago_in_words(log.created_at)%></small>
            </div>
            <!-- /Footer -->

        </article>
        <!-- /Panel -->
	<%end%>
		<!-- Separator -->
	        <div class="separator"></div>
        <!-- /Separator -->

</div>
<!-- /Timeline -->
<!--Pagination-->
<%= will_paginate @logs, previous_label: h("<"), next_label: h(">") %>
<!--/Pagination-->

app/views/players/index.html.erb
<h1>Utilisateurs<small> (<%= @count %>)</small></h1>

<div class="table-responsive">
  <div class="text-center">
      <%= paginate @players%><h3><small class="pull-right">Télécharger en <%= link_to 'format csv', players_path(format: :csv) %> | <%= link_to 'format pdf', players_path(format: :pdf) %></small><h3>
  </div>
  <table class="table table-condensed table-hover table-bordered">
    <thead>
        <tr>
            <th>#ID</th>
            <th>Nom</th>
            <th>Age</th>
            <th>Genre</th>
            <th>Date</th>

        </tr>
    </thead>
    <tbody>
      <% @players.each do |player|%>
        <tr>
          <td><%= player.id%></td>
          <td><%= player.username%></td>
          <td><%= player.age%></td>
          <td><%= player.genre%></td>
          <td><%= player.created_at.strftime("%d/%m/%Y  %H:%M")%></td>
        </tr>
      <%end%>
    </tbody>

  </table>
  <div class="text-center">
      <%= paginate @players%>
  </div>

</div>